import { Onest } from "next/font/google";
import "../styles/globals.css";

const onest = Onest({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={onest.className}>{children}</body>
		</html>
	);
}
